name: Deploy para GitHub Pages

on:
  # Executa a ação quando atualizações forem feitas na "branch main"
  push:
    branches: ["main"]

  # Permite que a ação seja executada manualmente na guia "Ações"
  workflow_dispatch:

# Define as permissões do GITHUB_TOKEN para permitir "deploy" para o GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um "deploy" simultâneo
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Extrai o repositório
        uses: actions/checkout@v5
      - name: Configura pnpm
        uses: pnpm/action-setup@v4
      - name: Configura Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Instala dependências
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Configura GitHub Pages
        uses: actions/configure-pages@v5
      - name: Envia o build para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
